-- MySQL Script generated by MySQL Workbench
-- Thu Jun 16 17:45:58 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema airbnb-clone
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `airbnb-clone` ;

-- -----------------------------------------------------
-- Schema airbnb-clone
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `airbnb-clone` DEFAULT CHARACTER SET utf8 ;
USE `airbnb-clone` ;

-- -----------------------------------------------------
-- Table `airbnb-clone`.`pais`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `airbnb-clone`.`pais` ;

CREATE TABLE IF NOT EXISTS `airbnb-clone`.`pais` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `airbnb-clone`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `airbnb-clone`.`usuario` ;

CREATE TABLE IF NOT EXISTS `airbnb-clone`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `pais_id` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(15) NULL DEFAULT NULL,
  `locatario` TINYINT NULL DEFAULT NULL,
  `anfitriao` TINYINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_usuario_pais1`
    FOREIGN KEY (`pais_id`)
    REFERENCES `airbnb-clone`.`pais` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `airbnb-clone`.`tipo_acomodacao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `airbnb-clone`.`tipo_acomodacao` ;

CREATE TABLE IF NOT EXISTS `airbnb-clone`.`tipo_acomodacao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `airbnb-clone`.`estado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `airbnb-clone`.`estado` ;

CREATE TABLE IF NOT EXISTS `airbnb-clone`.`estado` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `pais_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_estado_pais1`
    FOREIGN KEY (`pais_id`)
    REFERENCES `airbnb-clone`.`pais` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `airbnb-clone`.`cidade`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `airbnb-clone`.`cidade` ;

CREATE TABLE IF NOT EXISTS `airbnb-clone`.`cidade` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `estado_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_cidade_estado1`
    FOREIGN KEY (`estado_id`)
    REFERENCES `airbnb-clone`.`estado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `airbnb-clone`.`acomodacao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `airbnb-clone`.`acomodacao` ;

CREATE TABLE IF NOT EXISTS `airbnb-clone`.`acomodacao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tipo_acomodacao_id` INT NOT NULL,
  `usuario_id` INT NOT NULL,
  `cidade_id` INT NOT NULL,
  `cep` VARCHAR(8) NOT NULL,
  `rua` VARCHAR(45) NOT NULL,
  `numero` VARCHAR(3) NOT NULL,
  `complemento` VARCHAR(255) NULL DEFAULT NULL,
  `diaria` FLOAT(8,2) NOT NULL,
  `imagem_interior` VARCHAR(45) NOT NULL,
  `imagem_frontal` VARCHAR(45) NOT NULL,
  `imagem_adicional` VARCHAR(45) NULL DEFAULT NULL,
  `descricao` VARCHAR(255) NULL DEFAULT NULL,
  `capacidade` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_acomodacao_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `airbnb-clone`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_acomodacao_tipo_acomodacao1`
    FOREIGN KEY (`tipo_acomodacao_id`)
    REFERENCES `airbnb-clone`.`tipo_acomodacao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_acomodacao_cidade1`
    FOREIGN KEY (`cidade_id`)
    REFERENCES `airbnb-clone`.`cidade` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `airbnb-clone`.`comentario_acomodacao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `airbnb-clone`.`comentario_acomodacao` ;

CREATE TABLE IF NOT EXISTS `airbnb-clone`.`comentario_acomodacao` (
  `acomodacao_id` INT NOT NULL,
  `usuario_id` INT NOT NULL,
  `comentario` VARCHAR(255) NOT NULL,
  CONSTRAINT `fk_comentario_acomodacao_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `airbnb-clone`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comentario_acomodacao_acomodacao1`
    FOREIGN KEY (`acomodacao_id`)
    REFERENCES `airbnb-clone`.`acomodacao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `airbnb-clone`.`anuncio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `airbnb-clone`.`anuncio` ;

CREATE TABLE IF NOT EXISTS `airbnb-clone`.`anuncio` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `acomodacao_id` INT NOT NULL,
  `data_inicio` DATETIME NOT NULL,
  `data_fim` DATETIME NOT NULL,
  `valor` DECIMAL NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_anuncio_acomodacao1`
    FOREIGN KEY (`acomodacao_id`)
    REFERENCES `airbnb-clone`.`acomodacao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `airbnb-clone`.`locacao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `airbnb-clone`.`locacao` ;

CREATE TABLE IF NOT EXISTS `airbnb-clone`.`locacao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuario_locatario_id` INT NOT NULL,
  `acomodacao_id` INT NOT NULL,
  `valor` DECIMAL NOT NULL,
  `valor_multa` DECIMAL NULL DEFAULT NULL,
  `data_inicio` DATETIME NOT NULL,
  `data_fim` DATETIME NOT NULL,
  `checkin` TINYINT NULL DEFAULT NULL,
  `cancelamento` TINYINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_locacao_acomodacao1`
    FOREIGN KEY (`acomodacao_id`)
    REFERENCES `airbnb-clone`.`acomodacao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_locacao_usuario_locatario`
    FOREIGN KEY (`usuario_locatario_id`)
    REFERENCES `airbnb-clone`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `airbnb-clone`.`cartao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `airbnb-clone`.`cartao` ;

CREATE TABLE IF NOT EXISTS `airbnb-clone`.`cartao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `numero` VARCHAR(45) NOT NULL,
  `titular` VARCHAR(45) NOT NULL,
  `vencimento` DATE NOT NULL,
  `cvv` VARCHAR(45) NOT NULL,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_cartao_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `airbnb-clone`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `airbnb-clone`.`conforto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `airbnb-clone`.`conforto` ;

CREATE TABLE IF NOT EXISTS `airbnb-clone`.`conforto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `airbnb-clone`.`conforto_has_acomodacao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `airbnb-clone`.`conforto_has_acomodacao` ;

CREATE TABLE IF NOT EXISTS `airbnb-clone`.`conforto_has_acomodacao` (
  `conforto_id` INT NOT NULL,
  `acomodacao_id` INT NOT NULL,
  PRIMARY KEY (`conforto_id`, `acomodacao_id`),
  CONSTRAINT `fk_conforto_has_acomodacao_conforto1`
    FOREIGN KEY (`conforto_id`)
    REFERENCES `airbnb-clone`.`conforto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_conforto_has_acomodacao_acomodacao1`
    FOREIGN KEY (`acomodacao_id`)
    REFERENCES `airbnb-clone`.`acomodacao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;